// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9xPdfU4OQ4dsBh5sJZjh2FXRUJZxias',
    appId: '1:683211070413:web:9beb41f80cae7afe618284',
    messagingSenderId: '683211070413',
    projectId: 'auth-83a85',
    authDomain: 'auth-83a85.firebaseapp.com',
    storageBucket: 'auth-83a85.firebasestorage.app',
    measurementId: 'G-Y2LCEJGHSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHhPyAKNZWcs2OLj1hHENr5rUaO76qWu4',
    appId: '1:683211070413:android:1a632400a2d910fa618284',
    messagingSenderId: '683211070413',
    projectId: 'auth-83a85',
    storageBucket: 'auth-83a85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhbssCmZ5tv05F5p97B4GW-0T9PoKaYNA',
    appId: '1:683211070413:ios:0c87d337ac7542dc618284',
    messagingSenderId: '683211070413',
    projectId: 'auth-83a85',
    storageBucket: 'auth-83a85.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhbssCmZ5tv05F5p97B4GW-0T9PoKaYNA',
    appId: '1:683211070413:ios:0c87d337ac7542dc618284',
    messagingSenderId: '683211070413',
    projectId: 'auth-83a85',
    storageBucket: 'auth-83a85.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9xPdfU4OQ4dsBh5sJZjh2FXRUJZxias',
    appId: '1:683211070413:web:84b4ad59ec3793f1618284',
    messagingSenderId: '683211070413',
    projectId: 'auth-83a85',
    authDomain: 'auth-83a85.firebaseapp.com',
    storageBucket: 'auth-83a85.firebasestorage.app',
    measurementId: 'G-G31LH5C7BF',
  );
}
